specifications:
- name: ContainerRecipe
  status: revision
  spec_type: Profile
  use_cases_url: https://www.github.com/openschemas/spec-container
  version: 0.0.1
  parent_type: SoftwareSourceCode
- name: ContainerImage
  status: revision
  spec_type: Profile
  use_cases_url: https://www.github.com/openschemas/spec-container
  version: 0.0.1
  parent_type: Thing
